// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvnWgC7MzdVjCR_2Ly8gEmmHNBaBsZ-ZM',
    appId: '1:756742084141:android:d1c01faa0e2b7cd6ca4aa4',
    messagingSenderId: '756742084141',
    projectId: 'biblical-games',
    storageBucket: 'biblical-games.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxiPvVZ-f66IMIQTCHbHz2UFQT948hwQ',
    appId: '1:756742084141:ios:fd4acab4680b4c78ca4aa4',
    messagingSenderId: '756742084141',
    projectId: 'biblical-games',
    storageBucket: 'biblical-games.firebasestorage.app',
    iosBundleId: 'com.example.gameMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxiPvVZ-f66IMIQTCHbHz2UFQT948hwQ',
    appId: '1:756742084141:ios:fd4acab4680b4c78ca4aa4',
    messagingSenderId: '756742084141',
    projectId: 'biblical-games',
    storageBucket: 'biblical-games.firebasestorage.app',
    iosBundleId: 'com.example.gameMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPVxRT7_lBMMYDfWFj2XH4E7GBONTJXYY',
    appId: '1:756742084141:web:e89f3c9abda819c7ca4aa4',
    messagingSenderId: '756742084141',
    projectId: 'biblical-games',
    authDomain: 'biblical-games.firebaseapp.com',
    storageBucket: 'biblical-games.firebasestorage.app',
    measurementId: 'G-Q21R1HWDT3',
  );
}
